### ISSUE TITLE
Added word is not being "displayed" correctly

### ISSUE THREAD

**Issue by luthraprerna** [watson-developer-cloud/speech-to-text-utils#6]
<img width="765" alt="screen shot 2017-01-06 at 12 14 20 pm" src="https://cloud.githubusercontent.com/assets/22749897/21726215/d0752c9a-d409-11e6-980c-6515cedb0a26.png">

**Comment by germanattanasio** [comment]
How should we display the words ?

**Comment by luthraprerna** [comment]
In the above case, the added word IEEE should have been displayed as 'I triple E' but it is being displayed as IEEE. Anyway, fixed this in version 0.1.3.
