### ISSUE TITLE
Add multiple words to corpus -> Wrong JSON format

### ISSUE THREAD

**Issue by luthraprerna** [watson-developer-cloud/speech-to-text-utils#7]
<img width="1008" alt="screen shot 2017-01-09 at 4 54 20 pm" src="https://cloud.githubusercontent.com/assets/22749897/21785144/5284b8ca-d68c-11e6-9384-0c029592144c.png">

**Comment by germanattanasio** [comment]
I think this is related to the way you write the JSON. Take a look at:  [words.json](https://github.com/watson-developer-cloud/speech-to-text-utils/blob/master/test/resources/words.json)

**Comment by luthraprerna** [comment]
No, the format was correct but I realized that there was a bug in the code. Fixed in version 0.1.3
